### ISSUE TITLE
Cask 'stats' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by CheyiLin** [Homebrew/homebrew-cask#140411]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Trying to upgrade cask `stats` from 2.8.5 to 2.8.6, got error `Cask 'stats' is unavailable: No Cask with this name exists.`.

```bash
$ brew update-reset
... # (no error)

$ brew update
Already up-to-date.

$ brew outdated --cask --greedy
stats (2.8.5) != 2.8.6

$ $ brew upgrade -d -v --cask --greedy stats
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/formula.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/stats.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/cask.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/stats/.metadata/2.8.5/20230124190602.001/Casks/stats.rb.rb
Error: Cask 'stats' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Command that failed

brew upgrade --cask --greedy stats

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/formula.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/stats.rb
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/zacklin/Library/Caches/Homebrew/api/cask.json --time-cond /Users/zacklin/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//opt/homebrew/Caskroom/stats/.metadata/2.8.5/20230124190602.001/Casks/stats.rb.rb
Error: Cask 'stats' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  redis@6.2

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  kubernetes-cli

$ brew config
HOMEBREW_VERSION: 3.6.20-146-g4b3d64d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4b3d64d307c8aa7f364c3f854a0b4dc29d59ecd0
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b53ed519c7187a6c5498f1a9e74d1cc7eaae3abb
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
aquasecurity/trivy
bufbuild/buf
gabrie30/utils
homebrew/cask
homebrew/core
homebrew/services
ngrok/ngrok
teamookla/speedtest
```

**Comment by dmlemos** [comment]
Same problem with another cask 'xnviewmp'

```
❯ brew update-reset && brew update
==> Fetching /usr/local/Homebrew...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 77 (delta 26), reused 57 (delta 7), pack-reused 0
Unpacking objects: 100% (77/77), 92.37 KiB | 263.00 KiB/s, done.
From https://github.com/Homebrew/brew
 * [new branch]          dawidd6-patch-1                                   -> origin/dawidd6-patch-1
 * [new branch]          dependabot/bundler/Library/Homebrew/webrick-1.8.1 -> origin/dependabot/bundler/Library/Homebrew/webrick-1.8.1
 * [new branch]          less-agressive-core-tap                           -> origin/less-agressive-core-tap

==> Resetting /usr/local/Homebrew...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/abhimanyu003/homebrew-sttr...

==> Resetting /usr/local/Homebrew/Library/Taps/abhimanyu003/homebrew-sttr...
branch 'main' set up to track 'origin/main'.
Reset branch 'main'
Your branch is up to date with 'origin/main'.

==> Fetching /usr/local/Homebrew/Library/Taps/ameshkov/homebrew-tap...

==> Resetting /usr/local/Homebrew/Library/Taps/ameshkov/homebrew-tap...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/argon/homebrew-mas...

==> Resetting /usr/local/Homebrew/Library/Taps/argon/homebrew-mas...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/carlocab/homebrew-personal...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 18 (delta 9), reused 18 (delta 9), pack-reused 0
Unpacking objects: 100% (18/18), 8.01 KiB | 303.00 KiB/s, done.
From https://github.com/carlocab/homebrew-personal
 * [new branch]      bump-flang-15.0.0 -> origin/bump-flang-15.0.0
 * [new branch]      cp2k              -> origin/cp2k
 * [new branch]      meson-test        -> origin/meson-test
 * [new branch]      openblas-test     -> origin/openblas-test

==> Resetting /usr/local/Homebrew/Library/Taps/carlocab/homebrew-personal...
branch 'main' set up to track 'origin/main'.
Reset branch 'main'
Your branch is up to date with 'origin/main'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/jarun/homebrew-imgp...

==> Resetting /usr/local/Homebrew/Library/Taps/jarun/homebrew-imgp...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

Already up-to-date.
```

```
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

```
❯ brew config
HOMEBREW_VERSION: 3.6.20-146-g4b3d64d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4b3d64d307c8aa7f364c3f854a0b4dc29d59ecd0
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b2439adf3b60c0e598a8a2f82b8574b8849ccecb
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --new-window
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.39.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.7.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

```
❯ brew tap
abhimanyu003/sttr
ameshkov/tap
argon/mas
carlocab/personal
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
jarun/imgp
```

```
❯ brew outdated --cask
xnviewmp (1.4.1) != 1.4.2
```

```
❯ brew upgrade --debug --verbose --cask xnviewmp
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/dlemos/Library/Caches/Homebrew/api/formula.json --time-cond /Users/dlemos/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.2\)\ curl/7.64.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/xnviewmp.rb
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/dlemos/Library/Caches/Homebrew/api/cask.json --time-cond /Users/dlemos/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Upgrading 1 outdated package:
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-146-g4b3d64d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.2\)\ curl/7.64.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source//usr/local/Caskroom/xnviewmp/.metadata/1.4.1/20230127000936.805/Casks/xnviewmp.rb.rb
Error: Cask 'xnviewmp' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:342:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:351:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

**Comment by mkozjak** [comment]
Same issue with `bettertouchtool`:

```
> brew doctor
Your system is ready to brew.

> brew upgrade --cask bettertouchtool
==> Upgrading 1 outdated package:
Error: Cask 'bettertouchtool' is unavailable: No Cask with this name exists.

> brew --version
Homebrew 3.6.20-167-g7a5f614
Homebrew/homebrew-core (git revision 3c1408e72ea; last commit 2023-01-24)
Homebrew/homebrew-cask (git revision 3d6b738e19; last commit 2023-01-24)
```

**Comment by jakedgy** [comment]
This might be related to [changes that GIthub made to compression](https://github.com/orgs/community/discussions/45830) (and subsequently hashing) of automatically generated archives.

**Comment by jakedgy** [comment]
Same issue with `1password-cli`:

```sh
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  kubeval
  node@12
  
❯ brew upgrade --cask 1password-cli
==> Upgrading 1 outdated package:
Error: Cask '1password-cli' is unavailable: No Cask with this name exists.

❯ brew --version
Homebrew 3.6.20-167-g7a5f614
Homebrew/homebrew-core (git revision 957cf41d311; last commit 2023-01-31)
Homebrew/homebrew-cask (git revision 3b5df3214b; last commit 2023-01-31)
```

**Comment by miccal** [comment]
See this issue: https://github.com/Homebrew/brew/issues/13794

Setting
```
export HOMEBREW_NO_INSTALL_FROM_API=1
```
should help while this issue is being investigated.

**Comment by dmlemos** [comment]
@miccal I have tried that before, but sadly it doesn't work.

**Comment by bevanjkay** [comment]
@dmlemos Until this bug is squashed, try running `brew reinstall <token>` when you encounter this issue and the latest version should be installed for you.

**Comment by solzard** [comment]
As discussed in https://github.com/Homebrew/brew/issues/14463, it's important to delete an outdated cask file under `$(brew --prefix)/Caskroom`; otherwise, the same error will persist. 
The following command worked for me in dealing with `bettertouchtool` and `launchcontrol` issues:

```shell
export APP="<cask_name>"; rm -rf "$(brew --prefix)/Caskroom/$APP" && brew reinstall --cask --force "$APP"
```

**Comment by johnpicozzi** [comment]
Also seeing this issue with `lando`. The above export command didn't work in my case. The `brew reinstall <token>` did work.

**Comment by karlhorky** [comment]
Similar for me: As mentioned by @gromgit in his comment https://github.com/Homebrew/brew/issues/14463#issuecomment-1408652632, I fixed by issue with the `signal` cask doing the following:

Run `brew readall homebrew/cask`

If it errored out, run the following (this will remove any changes you've made in the tap):

```bash
brew untap --force homebrew/cask
brew tap homebrew/cask
```

Otherwise, if it ran through, run the following to manually delete the stale installation data and reinstall the cask:

```bash
rm -fr /opt/homebrew/Caskroom/signal
brew reinstall --cask --force signal
```

**Comment by vinkla** [comment]
I'm seeing this for `eloston-chromium` as well:
```
Error: Cask 'eloston-chromium' is unavailable: No Cask with this name exists.
```

**Comment by Dmole** [comment]
```
brew search --cask calibre 
==> Casks
calibre ✔


brew outdated
calibre (6.11.0) != 6.12.0
libreoffice (7.4.5) != 7.5.0

brew upgrade --greedy
==> Upgrading 5 outdated packages:
Error: Cask 'calibre' is unavailable: No Cask with this name exists.
```

**Comment by Rylan12** [comment]
Has this been resolved with the closing of https://github.com/Homebrew/brew/issues/14463?

**Comment by actuallymentor** [comment]
@Rylan12 I am encountering the issue right now so would assume not.

**Comment by gbstan** [comment]
I get this error **every day** in the past week for the cask "bettertouchtool".
I then do a `brew update --casks --force bettertouchtool` and it upgrades it correctly.
However, when an update to `bettertouchtool` becomes available (which happens almost daily), then I get again:
`Error: Cask 'bettertouchtool' is unavailable: No Cask with this name exists`
and need to upgrade manually again.

**Comment by KoheiKanagu** [comment]
I'm getting a 404 error on this cask.json, is this related to this issue?
https://formulae.brew.sh/api/cask.json

**Comment by actuallymentor** [comment]
@KoheiKanagu that is a known issue at [Homebrew/brew/issues/14489](https://github.com/Homebrew/brew/issues/14489) related to Github pages.

@Rylan12 FYI you closed the issue yesterday, it looks to be a problem still.

**Comment by Rylan12** [comment]
The 404 issues should be fixed (for real) now.

I'm still trying to reproduce the cask not found issue. I'll try with `bettertouchtool` and see if I can get it to happen. If possible, the next time you encounter the issue, can you check the `.metadata` directory of the cask and post it's contents?

The `.metadata` directory for an installed cask is located at `$(brew --caskroom bettertouchtool)/.metadata` (obviously replace `bettertouchtool` with the name of the problematic cask)
